### PR TITLE
Armadillo sound mappings

### PR DESCRIPTION
**Pull request by bangetto**

### CODE REVIEW

**Comment by bangetto** [comment]
I get this when I try to run the generator
```
C:\Users\-----\Desktop\mappings>java -cp MappingsGenerator.jar com.viaversion.map
pingsgenerator.MappingsOptimizer 1.20.5 1.20.3
Error: Could not find or load main class com.viaversion.mappingsgenerator.Mappin
gsOptimizer
Caused by: java.lang.ClassNotFoundException: com.viaversion.mappingsgenerator.Ma
ppingsOptimizer
```

**Comment by kennytv** [comment]
Replace `MappingsGenerator.jar` with the actual jar name, but otherwise I can also build and move it myself with the next snapshot

**Comment by bangetto** [comment]
I just forgot to remove the version number from the build name

**Review by kennytv — APPROVED** [review]
Thank you!

**Pull request merged**
